Repository supershy42/user, pull requests merged in 2024-12, with the labels that each got.

#8 User Profile View
  config/urls.py
  user_management/serializers.py
  user_management/tests.py
  user_management/urls.py
  user_management/views.py
Labels: feature

#9 Friend 기능 구현
  config/settings.py
  config/urls.py
  friend/__init__.py
  friend/admin.py
  friend/apps.py
  friend/migrations/0001_initial.py
  friend/migrations/__init__.py
  friend/models.py
  friend/serializers.py
  friend/services.py
  friend/tests.py
  friend/urls.py
  friend/views.py
Labels: feature

#14 로그인 시 is_active 상태 반환 추가
  user_management/serializers.py
  user_management/tests.py
  user_management/views.py
Labels: bug

#15 이메일 인증코드 전송 API
  user_management/migrations/0001_initial.py
  user_management/models.py
  user_management/serializers.py
  user_management/services.py
  user_management/urls.py
  user_management/views.py
Labels: feature

#17 Requirements 장고 버전 동기화
  requirements.txt
Labels: feature

#19 이메일 인증 완료 후 회원가입 완료하도록 수정
  user_management/migrations/0002_remove_user_is_active.py
  user_management/models.py
  user_management/serializers.py
  user_management/services.py
  user_management/tests.py
  user_management/urls.py
  user_management/views.py
Labels: refactoring

#21 CORS 설정
  config/settings.py
  requirements.txt
Labels: feature

#20 Response builder 구현
  config/custom_validation_error.py
  config/error_type.py
  config/response_builder.py
  requirements.txt
  user_management/serializers.py
  user_management/views.py
Labels: feature

#24 Response에서 상세한 status code 적용
  config/error_type.py
  config/response_builder.py
  user_management/serializers.py
  user_management/tests.py
  user_management/views.py
Labels: feature

#25 CustomMiddleware 추가
  config/asgi.py
  config/middleware.py
  config/settings.py
  config/urls.py
  friend/views.py
  requirements.txt
Labels: feature

#26 Minor modifications regarding Dockerfile
  Dockerfile
Labels: refactoring

#28 실시간 알림 기능 구현
  config/asgi.py
  config/settings.py
  requirements.txt
  user_management/consumers.py
  user_management/redis_utils.py
  user_management/routing.py
  user_management/tests.py
Labels: feature

#31 친구 요청 수락 시 채팅방 자동 생성
  config/middleware.py
  config/services.py
  config/settings.py
  friend/services.py
  friend/tests.py
  friend/views.py
  requirements.txt
Labels: feature

#33 친구 요청 알림 전송
  friend/services.py
  friend/views.py
  user_management/consumers.py
  user_management/services.py
Labels: feature

#36 Tournament notification 추가 및 UserProfileSerializer 수정
  config/services.py
  config/settings.py
  user_management/consumers.py
  user_management/serializers.py
Labels: feature

#37 친구 삭제 기능 구현
  config/services.py
  friend/migrations/0002_friendship_chatroom_id.py
  friend/models.py
  friend/serializers.py
  friend/services.py
  friend/urls.py
  friend/views.py
Labels: feature

#41 에러 응답에서 중첩된 상태 코드를 올바르게 추출하도록 수정
  config/response_builder.py
Labels: bug

#42 Websocket 연결 시 토큰 전달 방식 변경
  config/middleware.py
  requirements.txt
Labels: feature

#38 Send email API 구현
  config/custom_validation_error.py
  config/error_type.py
  config/response_builder.py
  friend/services.py
  user_management/consumers.py
  user_management/serializers.py
  user_management/services.py
  user_management/urls.py
  user_management/views.py
Labels: feature

#39 Enhance Dockerfile settings and add health check for database dependencies
  Dockerfile
  config/settings.py
  utils/entrypoint.sh
Labels: feature

#43 Env 설정
  config/settings.py
  requirements.txt
  user_management/redis_utils.py
Labels: feature

#46 DJANGO_SETTINGS_MODULE env 버그 수정
  config/asgi.py
Labels: bug

#44 User Profile 수정 API 구현
  config/services.py
  config/settings.py
  friend/services.py
  friend/views.py
  media/avatars/default.png
  user_management/migrations/0003_alter_user_avatar.py
  user_management/models.py
  user_management/serializers.py
  user_management/urls.py
  user_management/views.py
Labels: feature

#45 2FA API 구현
  config/middleware.py
  user_management/migrations/0003_user_is_2fa_enabled.py
  user_management/models.py
  user_management/serializers.py
  user_management/services.py
  user_management/urls.py
  user_management/views.py
Labels: feature

#49 친구 요청 목록 조회 기능 구현
  config/custom_validation_error.py
  config/error_type.py
  config/response_builder.py
  friend/services.py
  friend/urls.py
  friend/views.py
  user_management/migrations/0004_merge_0003_alter_user_avatar_0003_user_is_2fa_enabled.py
  user_management/migrations/0005_alter_user_avatar.py
Labels: feature, refactoring

#50 친구 요청 알림에 friend_request_id 필드 추가
  friend/services.py
Labels: refactoring

#51 User profile, Friend_request hotfix
  config/error_type.py
  config/services.py
  friend/services.py
  user_management/urls.py
  user_management/views.py
Labels: feature

#53 Search user
  config/response_builder.py
  user_management/urls.py
  user_management/views.py
Labels: feature

#55 친구 요청 응답 메시지 수정
  friend/services.py
  friend/views.py
Labels: feature

#54 Allowed hosts & install psycopg
  config/settings.py
  requirements.txt
Labels: feature

#56 친구 요청 거절해도 재전송 가능하도록 수정
  config/settings.py
  friend/services.py
Labels: feature

#57 Python 버전 수정 및 PostgreSQL 클라이언트 설치, API Gateway 요청 제한 설정
  Dockerfile
  config/settings.py
  requirements.txt
Labels: feature

#58 친구 차단 기능 구현
  config/error_type.py
  friend/migrations/0003_block.py
  friend/models.py
  friend/services.py
  friend/urls.py
  friend/views.py
Labels: feature
